all:
	gcc -Wall -Wshadow -g project2.c project2_test.c -o project2 && ./project2
#	valgrind --tool=memcheck --track-origins=yes --leak-check=full --verbose --log-file=memcheck.log ./project2 && cat memcheck.log | tail -n 1 
